name: hanyang_robot
channels:
  - robostack-humble
  - robostack-staging
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ros-humble-desktop
  - ros-humble-ros-gz
  - ros-humble-ros-gz-sim
  - gz-sim8
  - gz-tools2
  - gz-rendering8
  - libgz-sim8
  - setuptools=58.2.0
  - pip
  - pip:
      - coverage==7.6.10
